### ISSUE TITLE
Is there any way to access HttpRequest data by Injection Dependency?

### ISSUE THREAD

**Issue by lira92** [BorisWilhelms/azure-function-dependency-injection#10]
I have some data like headers on the request that I want to access in other layers without need to pass as parameter, I would like to access a instance injected which provide this information for me, like a IHttpContextAccessor in AspNetCore. Is it possible?

**Comment by BorisWilhelms** [comment]
I have researched and digged down the azure functions sdk and unfortunately haven't found any way to access this data beside of the HttpRequest.

**Comment by jnevins-gcm** [comment]
Can’t you get at it in the trigger binding data?

**Comment by lira92** [comment]
@jnevins-gcm Can you give me a example? I think that i didn't see this yet.

**Comment by jnevins-gcm** [comment]
In the BindingContext which you can get at through the Binding

https://github.com/Azure/azure-webjobs-sdk/blob/b798412ad74ba97cf2d85487ae8479f277bdd85c/src/Microsoft.Azure.WebJobs.Host/Bindings/BindingContext.cs

**Comment by BorisWilhelms** [comment]
I am not sure if this really helps? As far as I understand we are talking about a http triggered function where @lira92 wants to access http request data inside a service which gets injected into the function?

**Comment by jnevins-gcm** [comment]
Right - but the point is you can get a hook at binding time - where you create the IServiceScope. That means you can add the current function execution’s HttpRequestMessage for use in that IServiceScope - either via an AsyncLocal and a registration that uses it or a separate scoped wrapper service you create (e.g HttpRequestScope) which has it’s value set after the new IServiceScope is created, but before the injected service is resolved. 

That is

services.Add<MyMessageHeaderInfo>(sp => sp.Resolve<Http

**Comment by lira92** [comment]
@jnevins-gcm you could provide a PR for this approach in this repo. What you think about?

**Comment by jnevins-gcm** [comment]
sure but might be a few days...is the explanation unclear?

**Comment by lira92** [comment]
@jnevins-gcm I really didn't implement anything, but in some things I have doubts. What is "AsyncLocal" that you mention above? When you say binding code, you refer to code that in this repo is present on DependencyInjection/Bindings/InjectBinding.cs file?

**Comment by jnevins-gcm** [comment]
Yes that’s the binding code. 

Async local is a .net class for storing thread static data that flows through with async calls 

https://docs.microsoft.com/en-us/dotnet/api/system.threading.asynclocal-1?view=netframework-4.7.2

**Comment by BorisWilhelms** [comment]
While this seems to work, I will most probably not include this into the lib/nuget-package as this seems to be a very sepcific use-case. But you can still fork this project and include it for your needs.

**Comment by lira92** [comment]
@BorisWilhelms thanks for this great job, I had not seen that you have created a nuget package for this repo, because of this I suggested a possible PR to this repo. I would like to see some solution for this problem in your blog, for example. Would it possible?
