### ISSUE TITLE
Error Deploying to Azure

### ISSUE THREAD

**Issue by roend83** [BorisWilhelms/azure-function-dependency-injection#12]
This is working fine when debugging on my machine, but I'm getting the following error when deploying a function using this package to Azure:

> 

Error indexing method 'PurgePdfsFunction.Run' Cannot bind parameter 'processor' to type PurgePdfsProcessor. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.). |  
-- | --

Any idea what I'm doing wrong?

**Comment by BorisWilhelms** [comment]
See related issue https://github.com/BorisWilhelms/azure-function-dependency-injection/issues/11
