### ISSUE TITLE
'IFunctionInvocationFilter' is obsolete

### ISSUE THREAD

**Issue by chamikasandamal** [BorisWilhelms/azure-function-dependency-injection#14]
> Severity	Code	Description	Project	File	Line	Suppression State
> Warning	CS0618	'IFunctionInvocationFilter' is obsolete: 'Filters is in preview and there may be breaking changes in this area.'

Seems to be obsolete

**Comment by BorisWilhelms** [comment]
There is AFAIK currently no other mechanism. The message clearly says it is in preview and MAY be breaking changes in future. So it seems to be ok to use for the moment.
