### ISSUE TITLE
Is there anyway we could implement interface based typed factory?

### ISSUE THREAD

**Issue by rkbalu** [BorisWilhelms/azure-function-dependency-injection#15]
Is there any way we could achieve the below factory pattern in function app?
https://github.com/castleproject/Windsor/blob/master/docs/typed-factory-facility-interface-based.md? 

I really appreciate any guidance on this regards.

**Comment by BorisWilhelms** [comment]
While I think it will be quite hard to implement this with the Microsoft Dependency Injection, you could also have this with my Nuget package. This extension uses what ever IoC container is returned from the ServiceProviderBuilder. There is a package (https://github.com/volosoft/castle-windsor-ms-adapter) that wraps a Castle WIndsor container into an `IServiceProvider`. You can use that with my Autofac example in the readme.

**Comment by rkbalu** [comment]
Thanks @BorisWilhelms . I'll have a look at it.
