### ISSUE TITLE
Failure to deploy to Azure even with correct extensions.json

### ISSUE THREAD

**Issue by vincentvanderwalt** [BorisWilhelms/azure-function-dependency-injection#16]
Good morning,

Thanks for a great library !!!

I'm trying to deploy my function to azure, it's working fine locally.

I've included the targets file and can see the updated extensions file in the bin folder on build.

However, when I deploy to Azure I get the _Error indexing method 'XXXXXX.Run' Cannot bind parameter 'worker' to type IXXXXXX.. Make sure the parameter Type is supported by the binding._ error

Any ideas appreciated.

**Comment by Joehannus** [comment]
I'm getting this issue too. Please advice how to fix this. Locally in Visual Studio everything is working fine, but when deploying the functions to azure I'm getting the same errors - cannot bind parameter to type.

**Comment by vincentvanderwalt** [comment]
My functions work fine now. 
I'd made sure the Directory.Build.Targets file is actually being processed. When you publish you'll see a message to the effect of 'overwritten extenstions.json with one from build'

I also deploy using zip and ensure you delete existing files.

after that my functions worked fine. all bindings are pulled from keyvault

you can check the produced zip -> bin -> extensions.json to see if you're startup file is included
