### ISSUE TITLE
Not working with netcoreapp2.1?

### ISSUE THREAD

**Issue by martinnormark** [BorisWilhelms/azure-function-dependency-injection#17]
My function app is targeting `netcoreapp2.1` - is it supposed to work with that?

I'm getting the error:

```
[29-Oct-18 14:09:22] Error indexing method 'WebhookProcessor.Run'
[29-Oct-18 14:09:22] Microsoft.Azure.WebJobs.Host: Error indexing method 'WebhookProcessor.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'cc1' to type ICC1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

My project file looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>V2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.23" />
    <PackageReference Include="Willezone.Azure.WebJobs.Extensions.DependencyInjection" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

Startup class:
```csharp
using MyApp.Functions;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Hosting;
using Microsoft.Azure.WebJobs.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using Willezone.Azure.WebJobs.Extensions.DependencyInjection;

[assembly: WebJobsStartup(typeof(Startup))]
namespace MyApp.Functions
{
	internal class Startup : IWebJobsStartup
	{
		public void Configure(IWebJobsBuilder builder) =>
				builder.AddDependencyInjection<ServiceProviderBuilder>();
	}

	internal class ServiceProviderBuilder : IServiceProviderBuilder
	{
		private readonly ILoggerFactory _loggerFactory;

		public ServiceProviderBuilder(ILoggerFactory loggerFactory) =>
				_loggerFactory = loggerFactory;

		public IServiceProvider Build()
		{
			var services = new ServiceCollection();

			services.AddTransient<ICC1, CC1>();

			return services.BuildServiceProvider();
		}
	}

	public interface ICC1
	{
		int MyProperty { get; set; }
	}

	public class CC1 : ICC1
	{
		public CC1()
		{
			MyProperty = 42;
		}
		public int MyProperty { get; set; }
	}
}
```

My function `Run` method:
```csharp
[FunctionName("WebhookProcessor")]
public static async Task Run(
	[QueueTrigger("webhooks")] CloudQueueMessage queueMessage,
	[Table("webhooks")] CloudTable webhooksTable,
	[Blob("webhooks", FileAccess.ReadWrite)] CloudBlobContainer webhooksContainer,
	[Inject]ICC1 cc1,
	ILogger logger)
{
}
```

I have copied `Directory.Build.targets` into the folder of my project file.

Any ideas?

**Comment by f2calv** [comment]
No azure functions are supposed to target as follows **netstandard2.0** AFAIK
However even with that change I was struggling earlier today, basically DI works locally but upon upload to Azure I am continually getting a similar message to you;

> Error indexing method 'Functions.XYZ' Cannot bind parameter '_ABCSvc' to type IABC. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Comment by tjrobinson** [comment]
> No azure functions are supposed to target as follows netstandard2.0 AFAIK

Yep, changing my Azure Function project from targetting `netcoreapp2.1` to `netstandard2.0` resolved the "Make sure the parameter Type is supported by the binding." error in the original post.

**Comment by rasmuschristensen** [comment]
@f2calv When deploying to azure check out this issue https://github.com/BorisWilhelms/azure-function-dependency-injection/issues/11

I had the same issue and added the target into my project. Afterwards is also worked on azure.

**Comment by rasmuschristensen** [comment]
@martinnormark I'm having the same issue. Just downgraded to 2.0 and now it works as expected

**Comment by martinnormark** [comment]
I got it working by targeting `netstandard2.0`.

Problem is that it doesn't register `Startup` class as extension when targeting `netcoreapp2.1`: https://stackoverflow.com/q/53062309/2972

**Comment by ElanHasson** [comment]
It's odd because the template for an empty function project uses netcoreapp.

**Comment by shunsuke-kawai** [comment]
I was able to run Debug in 2.1.
Try build with target change to 2.0 -> find `extensions.json` in Bin -> copy to pjt dir -> change propertie to `Copy always` -> copy `Directory.Build.targets` -> target changed to 2.1 
I do not know the correct.

**Comment by StefH** [comment]
Works fine for me.

I'm able to debug locally.

And these versions are used:
```
Azure Functions Core Tools (2.3.148 Commit hash: f9b3db04f9833b431f1b001efb3e5783a169ebfc)
Function Runtime Version: 2.0.12210.0
```

**Comment by tank104** [comment]
This same issue for me @StefH  I wonder why it works for you. Out of the box?

**Comment by StefH** [comment]
@NimbleHive Can you try my example project here?
https://github.com/StefH/UnitTestingAzureFunctions

**Comment by tank104** [comment]
@StefH That works - but you are using netstandard2.0 not netcore 2.1

<TargetFramework>netstandard2.0</TargetFramework>

**Comment by StefH** [comment]
Ah yes. I noticed that the default function project from vs2017 uses netcore 2.1

However I did manually change to netstandard 2.0 because I dont need any netcore (yet).

**Comment by ranouf** [comment]
Hi 
Did you find a solution for .net core 2.2? 
I have the same issue, startup is not called

**Comment by Zordid** [comment]
Guys... this is so ridiculous. Why does anybody waste their precious time with MS... :-( I went down this route BECAUSE I need DI to use IHttpClientFactory. Only to find out now that with netcoreapp, the DI described here DOES NOT WORK?? Because in netstandard, the IHttpClientFactory does not work. This is a nightmare. The whole Microsoft universe is a nightmare for anybody into clean, precise coding... :(

**Comment by chtay1** [comment]
Zordid, we are using IHttpClientFactory with netstandard2.0 and Azure function DI via this package. What issue are you having?

**Comment by deadwards90** [comment]
For anyone still struggling with this, try updating to the latest Microsoft.NET.SDK.Functions (as of writing 1.0.25).

Seems they've fixed the issue, or at least this is now working for me.

**Comment by BorisWilhelms** [comment]
Hello, sorry for the late answer. Yes you need to change the `TargetFramework` of your function project to `netstandard2`. The reason is, that the metadatagenerator, that generates a json, that references the startup class only works for library projects. The Azure Functions SDK/Runtime has currently no support for Startup classes in the Function project.

**Comment by deadwards90** [comment]
@thinktecture it does work! They've recently released a update to the functions SDK to fix it. I had it working with a 2.1 Durable Function app in Azure yesterday.

You still need the directory targets bit in the project though.

**Comment by tank104** [comment]
I confirm this looks like its working for me now too.

**Comment by nhat-tong** [comment]
I confirm that this works for me with target .net core 2.1 and current version of Microsoft.NET.SDK.Functions (1.0.26). Thanks @dantheman999301 .

**Comment by ghstahl** [comment]
I have been looking around for anyone that has got azure functions working with .net core 2.2, no luck so far.  You might want to check an alternative way to get DI in an Azure Function.  https://github.com/ghstahl/Asp.Net-Core-2.1-app-as-a-tenant

**Comment by Athosone** [comment]
I also got this issue using .net core 2.1 and Microsoft.NET.SDK.Functions 1.0.26/1.0.28.
Despite the fact that my startup class get called, My service wont get injected and the function throw this binding error.....

**Comment by jitendriyag2** [comment]
It works for me as i forgot to Mention the Trigger Type, Please Find the example


`public static IActionResult EmailSend([HttpTrigger(AuthorizationLevel.Anonymous, "post")]HttpRequestMessage req,
            [SendGrid(ApiKey = "CustomSendGridKeyAppSettingName")]out SendGridMessage email,
            ILogger log){
///Own Logic
}`

**Comment by deadwards90** [comment]
@jitendriyag2 I'd move to using the built in DI that is now in Azure Functions unless you have a very good reason not to.

https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection
