### ISSUE TITLE
using IConfigurationRoot for the purpose of binding appsettings sections to classes

### ISSUE THREAD

**Issue by hansmbakker** [BorisWilhelms/azure-function-dependency-injection#19]
In ASP.Net Core you can [bind a `class` to a subsection ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#suboptions-configuration) in the `ConfigureServices` method because usually the `Configuration` is available there.

Is there a possibility to do that using your library?

(Injecting the plain IConfigurationRoot like in #3 is not what I'm looking for, I'm trying to register a class to a subsection of the appsettings)

**Comment by f2calv** [comment]
IConfigurationRoot with [strongly typed binding] is easy enough to add in, the snippet below should help, when IOptions are successfully configured I'm then passing a connection string as a parameter into the DbContext.

Note: I have my json files in a number of sub-folders so I had fun trying to find the best way for a correct path to them, non-working attempts commented out obviously. In the end I logged into the kudo console for the azure function to then navigate around the file system to see how things were laid out - in the event I would have to upload with a fixed path.

```
public void Configure(IWebJobsBuilder builder) => builder.AddDependencyInjection(ConfigureServices);

void ConfigureServices(IServiceCollection services)
{
    services.AddTransient<ITransientGreeter, Greeter>();
    services.AddScoped<IScopedGreeter, Greeter>();
    services.AddSingleton<ISingletonGreeter, Greeter>();

    var sBasePath = SharedF.AssemblyDirectory.Substring(0, SharedF.AssemblyDirectory.Length - 3);//remove the 'bin' folder
    //var sBasePath = AppContext.BaseDirectory;//??
    //var sBasePath = Directory.GetCurrentDirectory();//windows/system32
    //var sBasePath = AppDomain.CurrentDomain.BaseDirectory;//D:\Program Files (x86)\SiteExtensions\Functions\2.0.12134\64bit\
    //var sBasePath = Environment.CurrentDirectory;//D:\Windows\system32\

    var configBuilder = new ConfigurationBuilder()
        .SetBasePath(sBasePath)
        .AddJsonFile("appsettings.json", optional: false)
        .Build();

    services.AddOptions();
    services.Configure<AppConfig>(x => configBuilder.GetSection("AppConfig").Bind(x));
    services.Configure<ConnectionStrings>(x => configBuilder.GetSection("ConnectionStrings").Bind(x));

    var _appConfig = configBuilder.GetSection("AppConfig").Get<AppConfig>();
    var _connectionStrings = configBuilder.GetSection("ConnectionStrings").Get<ConnectionStrings>();

    if (_appConfig == null) throw new NullReferenceException("_appConfig == null, this should *never* happen!");
    if (_connectionStrings == null) throw new NullReferenceException("_connectionStrings == null, this should *never* happen!");

    services.AddDbContext<IEntities, Entities>(options => options.UseSqlServer(_connectionStrings.DSN));
}
```

**Comment by BorisWilhelms** [comment]
I guess the solution looks good. I close this issue. Feel free to reopen if you have any issues.
