### ISSUE TITLE
Add support for public property injection

### ISSUE THREAD

**Issue by StefH** [BorisWilhelms/azure-function-dependency-injection#22]
Would it also be possible to add support for public property injection via annotation?

Like
``` c#
[Inject]
public ISingletonGreeter SingletonGreeter;

[FunctionName("Greeter")]
public static IActionResult Run(
    [HttpTrigger(AuthorizationLevel.Function, "get")]HttpRequest req, ILogger logger)
{
    logger.LogInformation("C# HTTP trigger function processed a request.");

    return new OkObjectResult(SingletonGreeter.Greet());
}
```

**Comment by SeriousM** [comment]
Since the method is static there is no instance. The safest way is to use
method injection to avoid static reference problems. If you have too many
items to inject you could create a context object that gets all the
injections and use this in your method.

**Comment by StefH** [comment]
You are correct. I forgot that the class was static ;-)

Closing...

**Comment by woodpk** [comment]
Now that the classes and methods are no longer required to be static, is there any plan or possibility of providing class constructor injection with private or public properties:

        #region PROPERTIES & FIELDS 
        private readonly IQueryDispatcher _dispatcher;
        #endregion



        #region CONSTRUCTORS
        public PersonController(
                                                 [Inject] IQueryDispatcher dispatcher
                                              )
        {
            _dispatcher = dispatcher;
        }
