### ISSUE TITLE
Error indexing method 'GreeterFunction.Run'

### ISSUE THREAD

**Issue by kiwipiet** [BorisWilhelms/azure-function-dependency-injection#27]
I cloned the project and tried run the sample function and I am getting the following:
![image](https://user-images.githubusercontent.com/122649/50313059-17980d80-050f-11e9-8828-58517a1c21c5.png)

Any ideas?
I have .Net Core 2.1 and 2.2 installed, with VS 2017 15.9.4

**Comment by kobolsky** [comment]
Possible duplicate of #17.  Appears to work correctly if you target .Net Core 2.0 by updating your TargetFramework in your .csproj file to `<TargetFramework>netcoreapp2.0</TargetFramework>`

**Comment by kiwipiet** [comment]
@kobolsky [#17](https://github.com/BorisWilhelms/azure-function-dependency-injection/issues/17) says to target netstandard2.0, which is what this project is doing.
My question is that I am cloning [this project](https://github.com/BorisWilhelms/azure-function-dependency-injection) and it is not working as per my description above.

**Comment by kiwipiet** [comment]
I tried this at home and it all worked, so it looks like this was an environmental problem.  I'll recheck when I'm back on work on Monday.
