### ISSUE TITLE
Not working with Entity Framework 2.2

### ISSUE THREAD

**Issue by peef** [BorisWilhelms/azure-function-dependency-injection#28]
Adding DB context when `Microsoft.EntityFrameworkCore.SqlServer` v2.2.1 is used raise this error during app start:

_A host error has occurred
Willezone.Azure.WebJobs.Extensions.DependencyInjection: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Azure.WebJobs.IWebJobsBuilder.get_Services()'._

When downgrade to EF v2.1.4 then register DB context is OK.

**Comment by BorisWilhelms** [comment]
Duplicate of #26
