### ISSUE TITLE
IFunctionFilter deprecated

### ISSUE THREAD

**Issue by crookedbard** [BorisWilhelms/azure-function-dependency-injection#29]
DependencyInjectionWebJobsBuilderExtensions.cs
Line 62.
IFunctionFilter is obsolete

**Comment by BorisWilhelms** [comment]
Yes, they are marked as obsolete but this is currently the only way to implement scoping. In addition the obsolete message says it MAY break in future. 

If you know a better/stable solution to implement scopes, feel free to submit a PR.
