### ISSUE TITLE
Inject ILogger<T> or ILogger?

### ISSUE THREAD

**Issue by giemch** [BorisWilhelms/azure-function-dependency-injection#4]
Is it possible to wire up `ILogger` or `ILogger<T>` injection? I tried the following, and while `Thing` got successfully injected with an `ILogger<Thing>`, using it doesn't actually produce any logs.

`services.AddLogging();`
`services.AddSingleton<IThing, Thing>(sp => new Thing(sp.GetService<ILogger<Thing>>()));`

**Comment by gdodd1977** [comment]
Something to bare in mind. If you can't get what you need form MS.Dependency.Injecton, it's easy to plug in any other DI framework. I'm using LightInject in my version since it's a much deeper DI container.

**Comment by giemch** [comment]
I'd prefer to use the builtin DI if possible.

**Comment by daulet** [comment]
FWIW I have a [similar binding](https://github.com/daulet/Indigo.Functions#dependency-injection) that registers ```ILogger``` instance for you so you can use it anywhere in your dependency tree.
